import{a as _,i as h}from"./assets/vendor-weOZHO9C.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=o(r);fetch(r.href,s)}})();const b=document.querySelector(".modal-menu"),m=document.querySelector(".header__burger"),R=document.querySelectorAll(".modal-menu__nav a"),d=document.querySelector(".header");function w(){return b.classList.contains("modal-menu--open")}function j(){b.classList.add("modal-menu--open"),m.classList.add("is-open"),m.setAttribute("aria-expanded","true"),document.body.classList.add("no-scroll"),d==null||d.classList.remove("header__blur")}function L(){b.classList.remove("modal-menu--open"),m.classList.remove("is-open"),m.setAttribute("aria-expanded","false"),document.body.classList.remove("no-scroll"),d==null||d.classList.add("header__blur")}function H(){w()?L():j()}m.addEventListener("click",e=>{e.stopPropagation(),H()});document.addEventListener("keydown",e=>{e.key==="Escape"&&w()&&L()});document.addEventListener("click",e=>{if(!w())return;const t=e.target.closest(".header__burger"),o=e.target.closest(".modal-menu__container");!t&&!o&&L()});R.forEach(e=>e.addEventListener("click",L));const n={categoryList:document.querySelector(".categories-list"),productlist:document.querySelector(".products-list"),divNotFound:document.querySelector(".not-found"),loadMoreBtn:document.querySelector(".js-products-load-more"),loader:document.querySelector(".js-product-loader")},y={animals:new Map},U="https://paw-hut.b.goit.study",v={CATEGORIES:"/api/categories",PRODUCTS:"/api/animals"};_.defaults.baseURL=U;const F=async()=>{const{data:e}=await _(`${v.CATEGORIES}`);return e},S=async(e,t)=>{const{data:o}=await _(`${v.PRODUCTS}`,{params:{limit:t,page:e}});return o.animals.forEach(a=>{y.animals.set(a._id,a)}),console.log(y),o},P=async({categoryId:e,page:t=1,limit:o=9})=>{const{data:a}=await _(`${v.PRODUCTS}`,{params:{categoryId:e,page:t,limit:o}});return a.animals.forEach(r=>{y.animals.set(r._id,r)}),console.log(y),a},z=e=>{const t=e.map(({_id:o,name:a})=>`<li class="categories__item">
   <button class="categories__btn" data-category-id="${o}" type="button">${a}</button>
 </li>
`).join("");n.categoryList.innerHTML=t},g=e=>{const t=e.map(({_id:o,image:a,species:r,name:s,categories:l,age:q,gender:I,behavior:k})=>{const A=`
                    <ul class="product-card__categories">
                        ${l.map(N=>`<li class="product-card__category">${N.name}</li>`).join("")}
                    </ul>
                `;return`
            <li class="product-card" data-id="${o}">
                <article class="product-card__body">
                
                <div class="product-card__image-wrapper">
                    <img class="product-card__image" src="${a}" alt="${r}" loading="lazy" width="392" height="309"/>
                </div>
                    
                    <p class="product-card__title">${r}</p>
                    <h3 class="product-card__name">${s}</h3>

                    ${l.length?A:""}
            
                    <ul class="product-card__meta">
                        <li class="product-card__meta-item product-card__meta-item--age">${q}</li>
                        <li class="product-card__meta-item product-card__meta-item--gender">${I}</li>
                    </ul>
            
                    <p class="product-card__info">${k}</p>
                    <button class="product-card__btn product-card__btn--learnMore" data-modal-id=${o} type="button">
                        Дізнатись більше
                    </button>
                </article>
            </li>`}).join("");n.productlist.insertAdjacentHTML("beforeend",t)},T=()=>{const e=window.innerWidth;return e>=1440?"desktop":e>=768?"tablet":"mobile"},B=e=>{switch(e){case"desktop":return 9;case"tablet":case"mobile":default:return 8}},D=(e,t=300)=>{let o;return(...a)=>{clearTimeout(o),o=setTimeout(()=>e(...a),t)}},x=e=>{document.querySelectorAll(".categories__btn--active").forEach(o=>o.classList.remove("categories__btn--active")),e.classList.add("categories__btn--active")},O=()=>{const e=document.querySelector(".product-card");if(!e)return;const{height:t}=e.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})},$=()=>{n.productlist.innerHTML=""};function M(){n.loader.classList.remove("hidden")}function E(){n.loader.classList.add("hidden")}function G(){n.loadMoreBtn.classList.remove("hidden")}function K(){n.loadMoreBtn.classList.add("hidden")}function p(e,t){e<t?G():K()}let f=T(),c=1,u="all",i;const W=async()=>{try{const e=await F();z([{_id:"all",name:"Всі"},...e]);const o=document.querySelector(".categories__btn");o&&o.classList.add("categories__btn--active")}catch(e){console.log(e),h.error({message:"Oops, something went wrong!"})}},J=D(async()=>{const e=T();e!==f&&(f=e,c=1,await C())},300);window.addEventListener("resize",J);const C=async()=>{$(),M();try{const e=B(f),{animals:t,totalItems:o}=await S(c,e);g(t),i=Math.ceil(o/e),console.log(i),p(c,i)}catch(e){console.log(e),h.error({message:"Oops, something went wrong!"})}finally{E()}},Q=async e=>{if(e.target.nodeName!=="BUTTON")return;u=e.target.dataset.categoryId,c=1;const t=B(f);$(),x(e.target),n.divNotFound.classList.remove("not-found--visible"),M();try{if(u==="all"){const{animals:o,totalItems:a}=await S(c,t);g(o),i=Math.ceil(a/t),console.log(i),p(c,i)}else{const{animals:o,totalItems:a}=await P({categoryId:u,page:c,limit:t});o.length===0&&n.divNotFound.classList.add("not-found--visible"),g(o),i=Math.ceil(a/t),p(c,i)}}catch(o){console.log(o),h.error({message:"Oops, something went wrong!"})}finally{E()}};n.categoryList.addEventListener("click",Q);n.loadMoreBtn.addEventListener("click",async()=>{c+=1;const e=B(f);M();try{if(u==="all"){const{animals:t}=await S(c,e);g(t),O(),p(c,i)}else{const{animals:t}=await P({categoryId:u,page:c,limit:e});t.length===0&&n.divNotFound.classList.add("not-found--visible"),g(t),O(),p(c,i)}}catch(t){console.log(t),h.error({message:"Oops, something went wrong!"})}finally{E()}});W();C();
//# sourceMappingURL=index.js.map
